language: node_js
node_js:
  - "stable"
script:
  - npm install
  - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_KEY_SECRET
    bucket: "dev-parkingnotifier"
    region: "us-west-1"
    local_dir: build
    skip_cleanup: true
    acl: public_read
    on:
      branch: dev