language: node_js
node_js:
  - "10"
cache:
  - directories
    - node_modules
  - "stable"
script:
  - cd frontend
  - npm install
  - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_KEY_SECRET
    bucket: "parkingnotifier"
    region: "us-west-2"
    local_dir: build
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
